### ISSUE TITLE
Marks in fringe stop working properly

### ISSUE THREAD

**Issue by choltz** [Andrew-William-Smith/evil-fringe-mark#1]
Repro steps (Emacs 26.1)
1. Open clean emacs with no packages loaded
2. Open an empty buffer
2. M-x evil-mode
3. M-x evil-fringe-mark-mode
4. Add four lines to the file
```
  123
  123
  123
  123
```
5. Go the first line
6. Add marks a-d in the first four lines
```
a 123
b 123
c 123
d 123
```
7. Go to the first line
8. Type mb

Expected Results:
The buffer should look like this:
```
b 123
  123
c 123
d 123
```
Actual Results:
The buffer looks like this:
```
a 123
  123
c 123
d 123
```

**Comment by Andrew-William-Smith** [comment]
Thanks for reporting this issue!  The reason the second mark (b) does not replace the first (a) seems to lie within how Emacs determines which fringe overlays to display if two are set for the same line.  Basically, the bitmap it displays is the one assigned an overlay at an earlier point in the file; thus, marks placed closer to the beginning of each line (say, on the “1” in your example) will always be displayed over marks toward the end of the line (on the “3”).  If two overlays are placed at the *same* point, however, it seems to be indeterminate which one is displayed.

I can see how the current behaviour is confusing; I’ll add an option to always overwrite the bitmap in the fringe, regardless of line position or which mark was placed first.  @choltz, does that sound good to you?

**Comment by choltz** [comment]
Sounds good to me. Thank you!

**Comment by Andrew-William-Smith** [comment]
Sorry for the late response; I've been on vacation for a week.  This issue should be fixed in https://github.com/Andrew-William-Smith/evil-fringe-mark/commit/fdb147d5ec8fbe087c73604374b3d491f143f2b2; could you update your installation of this package and see if it conforms to your expectations?  (If you installed from MELPA, it may take a few hours to update.)

I added a boolean configuration value `evil-fringe-mark-always-overwrite` that controls whether or not the bitmap displayed in the fringe for a line is the most recently placed or the closest to the fringe.  This value is set to `t` by default, so you should **not** have to update your configuration to achieve the behaviour you'd expect—which definitely makes more sense than the old behaviour.  I made this a configuration option instead of a fixed behaviour to prevent [workflow disruptions](https://xkcd.com/1172/), in case anyone preferred the line position-based display.

**Comment by choltz** [comment]
Thank you for taking the time to look into this.

I'm still seeing the same issue. When I complete the test case described above, the buffer looks like this:
```
a 123
  123
c 123
d 123
```
To ensure I had the correct copy of evil-fringe-mark, I cloned this repo and referenced it in my .emacs startup, instead of relying on melpa.

To be thorough, I also explicitly set `(setq evil-fringe-mark-always-overwrite t)`, but the result was the same.

**Comment by Andrew-William-Smith** [comment]
While implementing a solution to Issue #3, I changed the behaviour such that `evil-fringe-mark-always-overwrite` ensures that only one bitmap is placed per line; all previous bitmaps are deleted, but enqueued for reinsertion if the mark that replaced them is moved.  Since you've already replaced your MELPA install with a clone of the repository, could you try out the latest commit on the `develop` branch (52ce92ea45aedb9cef7c038bd04fbe13487ec9fe)?

Here's a demo of it working on my machine:

![evil-fringe-mark Overwrite Preview](https://thumbs.gfycat.com/FlashyCreamyAsiantrumpetfish-max-14mb.gif)

(Also, please ensure that the package installed from MELPA is completely removed from your `load-path`.  Thanks!)

**Comment by choltz** [comment]
I plugged in the develop branch and it worked great. And it remembers the first mark if I move the second mark to a new line. Good stuff.

**Comment by Andrew-William-Smith** [comment]
Great!  I've merged the `develop` branch into `master`, so it should be available on MELPA within a few hours.  Thank you for helping to improve `evil-fringe-mark`!
